### ISSUE TITLE
Version conflict with black

### ISSUE THREAD

**Issue by rspeer** [thomasthiebaud/poetry-githooks#9]
With the current version constraints, I can't have poetry-githooks and black 22 installed at the same time using Poetry.

`poetry-githooks` requires `click ^7.1.2`, which implies `click < 8.0`. `black 22.1` requires `click >= 8.0`. Poetry's dependency solver has a very hard time figuring out that it needs to use an older version of `black` to resolve the conflict.

Assuming that `click` hasn't broken functionality that you need, could you update the dependencies of poetry-githooks to allow 8.x versions of `click`?

Thanks.

**Comment by thomasthiebaud** [comment]
Hi @rspeer, thanks for opening an issue. I'll have a look asap

**Comment by thomasthiebaud** [comment]
It should be fixed with version 2.0
